package GuiTileMapThing;

public enum BattleState {
    BATTLE_START,
    BATTLE_DECISION,
    BATTLE_SELECTMOVE,
    BATTLE_ALLYMOVE,
    BATTLE_ENEMYMOVE,
    BATTLE_SWITCH,
    BATTLE_ITEM,
    BATTLE_RUN,
    BATTLE_MESSAGE,
    BATTLE_LOSE,
    BATTLE_WIN,
    BATTLE_END,
    BATTLE_CHANGEPOKEMON,
}
